; LLVM IR generated by DSL Compiler
; Author: WASIM SHARAFATH M Y | RA2311026050171 | SRMIST Trichy
source_filename = "dsl_program"
target triple = "x86_64-pc-linux-gnu"

@.fmt_int = private constant [4 x i8] c"%d\0A\00"
@.fmt_flt = private constant [4 x i8] c"%f\0A\00"
@.fmt_str = private constant [4 x i8] c"%s\0A\00"
declare i32 @printf(i8*, ...)
declare i32 @scanf(i8*, ...)

@.str0 = private unnamed_addr constant [15 x i8] c"Greater than 25\00"
@.str1 = private unnamed_addr constant [12 x i8] c"Not greater\00"

define i32 @main() {
entry:
  %x = alloca i32
  %t0 = add i32 0, 10
  store i32 %t0, i32* %x

  %y = alloca i32
  %t1 = add i32 0, 20
  store i32 %t1, i32* %y

  %result = alloca i32

  %t2 = load i32, i32* %x
  %t3 = load i32, i32* %y
  %t4 = add i32 %t2, %t3
  store i32 %t4, i32* %result

  %t5 = load i32, i32* %result
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_int, i32 0, i32 0), i32 %t5)

  %t6 = load i32, i32* %result
  %t7 = icmp sgt i32 %t6, 25
  br i1 %t7, label %L0, label %L1

L0:
  %t8 = getelementptr inbounds [15 x i8], [15 x i8]* @.str0, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t8)
  br label %L2

L1:
  %t9 = getelementptr inbounds [12 x i8], [12 x i8]* @.str1, i32 0, i32 0
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_str, i32 0, i32 0), i8* %t9)
  br label %L2

L2:
  %counter = alloca i32
  %t10 = add i32 0, 0
  store i32 %t10, i32* %counter
  br label %L3

L3:
  %t11 = load i32, i32* %counter
  %t12 = icmp slt i32 %t11, 5
  br i1 %t12, label %L4, label %L5

L4:
  %t13 = load i32, i32* %counter
  call i32 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @.fmt_int, i32 0, i32 0), i32 %t13)
  %t14 = load i32, i32* %counter
  %t15 = add i32 %t14, 1
  store i32 %t15, i32* %counter
  br label %L3

L5:
  ret i32 0
}
